### PR TITLE
[MRG] Temporal weighting

### LINKED ISSUE #22: Temporal weighting of error
Currently it is possible to include only the part t>t_start in the calculation of error. It would be nice to be able to weight differently different parts of the traces. Typically, with responses to pulses, we might want to weight the onset and offset of the pulse more strongly. A simple way would be to provide a weight trace, of the same size as the other traces.

### PR DESCRIPTION
**Pull request by mstimberg**
This adds a simple temporal weighting factor to `MSEMetric`. Instead of `t_start` you can provide `t_weights`, a vector of values of the same size as the trace that gets multiplied with the error (i.e. scales the squared error in the case of `MSEMetric` ). For simplicity, it cannot be combined with `t_start`.

Closes #22

### CODE REVIEW

**Comment by mstimberg** [comment]
Somewhat forgot about this PR. @romainbrette, what do you think?

**Comment by romainbrette** [comment]
It runs, but does it apply also to refine?

**Comment by mstimberg** [comment]
> It runs, but does it apply also to refine?

Oops, good catch! No it didn't, but now it does :)

**Comment by romainbrette** [comment]
What does the error correspond to now? mean(t_weight*error)?

**Comment by mstimberg** [comment]
> What does the error correspond to now? mean(t_weight*error)?

Yes. I now realize that we should maybe make this clearer in the documentation. Weighting the first part of the trace as 0 or using `t_start` is similar, but it will not give the same result for the error – in the former case the error is considered 0 (but included in the mean) and in the latter it is simply ignored.

We could renormalize things by considering the total weight (so only the relative weights would matter)?

**Comment by romainbrette** [comment]
for example with something like `t_weights = t_weights/(sum(t_weights)*dt)` ?

**Comment by romainbrette** [comment]
En tout cas ça marche!

**Comment by romainbrette** [comment]
Ah non ça ne doit pas être exactement ça

**Comment by romainbrette** [comment]
(la normalisation je veux dire)

**Comment by mstimberg** [comment]
I guess
```
t_weights = len(t_weights)*t_weights/sum(t_weights)
```
would work?

**Comment by romainbrette** [comment]
yes that seems rights (ie `t_weights/mean(weights)`).

**Comment by mstimberg** [comment]
I implemented the normalization of the weights. This makes sure that using `t_start` generates the same error as using `t_weights` with zero for time points <  `t_start` and any kind of constant value for the other time points.
Currently, the weights weigh the *squared* error, or in other words the residual is weighted by the square root of the provided weight.  Not sure whether this is the best approach, especially given that the `normalization` scales the residual and not the squared error.

**Comment by mstimberg** [comment]
Discussed with @romainbrette and decided that applying the weighting to the squared error is ok. After all, users will chose this value somewhat arbitrarily anyway. Going ahead with the merge.

**Pull request merged**
